### PR TITLE
[Fix] Update rotate-screen prop-types with class-name

### PR DESCRIPTION
**Pull request by craighillwood**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Feature (non-breaking change which adds functionality)
- [ ] Code style update
- [ ] Refactor (refactoring or adding test which isn't a fix or add a feature)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

**Did you test your solution?**

- [ ] I lightly tested it in one browser
- [ ] I deeply tested it in several browsers
- [ ] I wrote tests around it (unit tests, integration tests, E2E tests)

## Problem Description
A warning appeared in the console caused by `RotateScreen` not having `className` as a `propTypes`.

image

## Solution Description
Update `RotateScreen` `propTypes` with `className`.

## Side Effects, Risks, Impact
This shouldn't break anything.

- [ ] N/A

**Aditional comments:**

### CODE REVIEW

**Comment by neo** [comment]
can you please also make it emit an event on orientation change?

**Comment by craighillwood** [comment]
> can you please also make it emit an event on orientation change?

@neo I sure can, by "event" do u mean calling a function that is sent via props?

**Comment by neo** [comment]
yup, would be helpful for some use cases

**Review by neo — APPROVED** [review]

**Comment by craighillwood** [comment]
We will target this [issue](https://github.com/Jam3/react-ui/pull/8#issuecomment-561693821) in another PR. cc: @neo

**Pull request merged**
